# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
