# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0002_auto_20170714_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersList',
            new_name='User',
        ),
    ]
