# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0003_auto_20170714_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
