# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0005_auto_20170714_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='address_book/static/img/'),
        ),
    ]
