# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0006_auto_20170714_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
