# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0007_auto_20170714_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
